LOG_LEVEL: INFO # DEBUG, INFO, WARNING, ERROR, CRITICAL

# Database
TIMESCALEDB_DB_HOST: 192.168.56.106
TIMESCALEDB_DB_USER: lilee
TIMESCALEDB_DB_PASSWD: Lilee1234
TIMESCALEDB_DB_NAME: commerce
DB_MIGRATION_REVISION: head

# Auth
SECRET_KEY: 73897bec-fd81-44c8-927d-4b3a9773f344
JWT_ALGORITHM: HS256

