LOG_LEVEL: INFO # DEBUG, INFO, WARNING, ERROR, CRITICAL

# Database
TIMESCALEDB_DB_HOST: 192.168.56.106
TIMESCALEDB_DB_USER: lilee
TIMESCALEDB_DB_PASSWD: Lilee1234
TIMESCALEDB_DB_NAME: commerce
DB_MIGRATION_REVISION: head

# Auth
SECRET_KEY: 40bc5196-dd3f-484d-ae52-7b151a9fd8ab
JWT_ALGORITHM: HS256

