LOG_LEVEL: INFO # DEBUG, INFO, WARNING, ERROR, CRITICAL
WEB_API_SERVER_HOST: web_api_server:8000

# Database
TIMESCALEDB_DB_HOST: timescaledb
TIMESCALEDB_DB_USER: default
TIMESCALEDB_DB_PASSWD: default1234
TIMESCALEDB_DB_NAME: commerce
DB_MIGRATION_REVISION: head

# Auth
SECRET_KEY: 73897bec-fd81-44c8-927d-4b3a9773f344
JWT_ALGORITHM: HS256

